#!/usr/bin/env python3
# Generated by ChatGPT
# Used to generate random input

import random
import argparse

NUCLEOTIDES = ['A', 'U', 'C', 'G']

def generate_rna(length):
    return ''.join(random.choice(NUCLEOTIDES) for _ in range(length))

def main():
    parser = argparse.ArgumentParser(description="Generate RNA sequences into separate files")
    parser.add_argument("-l", "--length", type=int, required=True,
                        help="Length of each RNA sequence")
    parser.add_argument("-n", "--num", type=int, required=True,
                        help="Number of sequences to generate")

    args = parser.parse_args()

    filenames = []

    for i in range(args.num):
        seq = generate_rna(args.length)
        fname = f"synthetic_seq_{i}.seq"
        filenames.append(fname)

        with open(fname, "w") as f:
            f.write(";Input generated by synthetic.py\n")
            f.write("Synthetic Input " + str(i) + "\n")
            f.write(seq + "\n")

    with open("synthetic_sequences.txt", "w") as f:
        for name in filenames:
            f.write("synthetic/" + name + "\n")

if __name__ == "__main__":
    main()

