/* ECE213 Final Project
 * Authors: Francisco Gutierrez, Jaehyung Lim, Sean Lipps
 *
 * Code Nussinov Algorithm
 * Reference Python: https://github.com/cgoliver/Nussinov
 *
 * Date of Creation: 2/24/26
 * Date Last Modified: 2/25/26
 */



#include <cstdlib>
#include <cstdio>
#include <cstring>

#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <cctype>


#include <bits/stdc++.h> // max function

#include "nussinov.cuh"


void show_DP(int* DP, int N){
  printf("Showing DP scores: \n");
  for(int i = 0; i<N; i++){
    for(int j = 0; j<N; j++){
      if(i < j - MIN_LOOP_LENGTH ) {
        printf("%3d ", DP[triInd(i, j, N)] );
      } else {
        printf("    ");
      } }
    printf("\n");
  }
}

// Parser generated by Gemini
// This function takes in a vector of .seq files and returns a vector of them parsed
std::vector<std::string> getCleanedSequences(const std::vector<std::string>& fileNames) {
    std::vector<std::string> allSequences;

    for (const std::string& fileName : fileNames) {
        std::ifstream file(fileName);
        if (!file.is_open()) {
            std::cerr << "Could not open file: " << fileName << std::endl;
            continue;
        }

        std::string line;
        std::string currentSequence = "";
        bool headerSkipped = false;

        while (std::getline(file, line)) {
            if (line.empty() || line[0] == ';') continue;

            if (!headerSkipped) {
                headerSkipped = true;
                continue;
            }

            for (char c : line) {
                if (std::isspace(c) || c == '1') continue;
#ifdef SEQ_N
                if (currentSequence.length() >= SEQ_N) break;
#endif
                currentSequence += c;
            }
#ifdef SEQ_N
            if (currentSequence.length() >= SEQ_N) break;
#endif
        }

        if (!currentSequence.empty()) {
            allSequences.push_back(currentSequence);
        }
        file.close();
    }
    return allSequences;
}

void traceback(int i, int j, cell_ind* structure, int* DP, const uint8_t* seq, int* trace_len, int N) {
  if (j<=i){
    return;
  } else if ( DP[N*i+ j] == DP[N*i+ j-1] ){
    traceback(i, j-1, structure, DP, seq, trace_len, N);
  } else {
    for(int k = i; k < j-MIN_LOOP_LENGTH; k++) {
      if(pair_check(seq, k, j)){
        if (k-1<0) {
          if( DP[N*i+ j] ==  DP[N*(k+1)+ j-1] + 1) {
            structure[*trace_len].x = k;
            structure[*trace_len].y = j;
            (*trace_len)++;
            traceback(k+1, j-1, structure, DP, seq, trace_len, N);
            break;
          }
        } else if ( DP[N*i+j] == (DP[N*(i)+k-1] + DP[N*(k+1)+ j-1] + 1)) {
          // add the pair (j,k) to our list of pairs
          structure[*trace_len].x = k;
          structure[*trace_len].y = j;
          (*trace_len)++;
          // move the recursion to two substructures formed by this pairing
          traceback(i, k-1, structure, DP, seq, trace_len, N);
          traceback(k+1, j-1, structure, DP, seq, trace_len, N);
          break;
        }
      }
    }
  }
}

void write_structure(int N, cell_ind* structure, int* struct_len){
  char* dot_bracket = (char*)malloc(2*N+1);
  dot_bracket[N] = '\0';
  for(int i = 0; i<N; i++)
    dot_bracket[i]='.';

  for(int i = 0; i < *struct_len; i++){
    dot_bracket[std::min(structure[i].x, structure[i].y)] = '(';
    dot_bracket[std::max(structure[i].x, structure[i].y)] = ')';
  }

  bool put_comma = false;
  printf("('%s', [", dot_bracket);
  for(int i = 0; i < *struct_len; i++){
    if(put_comma) printf(", ");
    printf("(%d, %d)", structure[i].x, structure[i].y);
    put_comma = true;
  }
  printf("])\n");
  
  free(dot_bracket);
}

void nussinov_cpu(uint8_t* seq, int* DP, int N){
  int cell_value;
  int j;

  for(int k = MIN_LOOP_LENGTH+1; k < N; k++){
    for(int i = 0; i < (N-k); i++){
      j = i+k;

      if (i >= j- MIN_LOOP_LENGTH)
        cell_value = 0;
      else {
#if MIN_LOOP_LENGTH == 0
        // we do not want to go out of bounds
        if(j==0) cell_value = 0;
        else cell_value = triInd_safe(i, j-1, N, DP);
#else
        cell_value = triInd_safe(i, j-1, N, DP);
#endif


        // iterates through possible pairs for a cell
        for(int t = i; t< j-MIN_LOOP_LENGTH; t++){
          // Check paired scores (if pairing exists)
          if (pair_check(seq, t, j)) {
            int pairing1 = 0;
            int pairing2 = 0;

            if(i < (t-1)-MIN_LOOP_LENGTH)
              pairing1 = triInd_safe(i, t-1, N, DP);
            if(t+1 < (j-1)-MIN_LOOP_LENGTH)
              pairing2 = triInd_safe(t+1, j-1, N, DP);

            cell_value = std::max(cell_value, pairing1 + pairing2 + 1);
          }
        }
      }

      DP[triInd(i, j, N)] = cell_value;
    }
  }
}

/**
 * @brief Wrapper for running nussinov algorithm. 
 *
 * @param seqs array rna sequences contiguous and with 2 bit encoding
 * @param seqs_offsets determines what item endsin what place
 * @param N determines number of rna sequences in that encoded array
 */
void nussinov(uint8_t* seqs, uint32_t* seq_offsets, uint32_t* seq_lengths, uint32_t* dp_offsets, uint32_t N, uint32_t total_bytes, uint32_t total_dp_cells){

#ifdef CPU_TARGET
  Timer timerCpu;
  long accTime = 0; // timers only count one kernel at a time, so they must be accumulated
  int* cpu_batched_DP = (int*)calloc(total_dp_cells, sizeof(int));
  int start_seq = 0;

  // Running nussinov 
  for(size_t num_seq = 0; num_seq < N; num_seq++) {
    uint32_t len = seq_lengths[num_seq];
    uint8_t* curr_seq = &seqs[seq_offsets[num_seq]];
    int* curr_DP = &cpu_batched_DP[dp_offsets[num_seq]];

    timerCpu.Start();
    nussinov_cpu(curr_seq, curr_DP, len);
    accTime += timerCpu.Stop();

#ifdef DEBUG
    show_DP(curr_DP, N);
#endif
    int* DP_square = (int*)calloc(len * len, sizeof(int));
    cell_ind* structure = (cell_ind*)malloc(2 * len * sizeof(cell_ind));
    int struct_len = 0;

    // Copy uptriangular matrix to real NxN Matrix
    for(int k = MIN_LOOP_LENGTH+1; k < len; k++){
      for (int i = 0; i < len-k; i++){
        int j = i+k;
        DP_square[len*i+j] = curr_DP[triInd(i, j, len)];
      }
    }

    traceback(0, len-1, structure, DP_square, curr_seq, &struct_len, len);

    write_structure(len, structure, &struct_len);

    free(DP_square);
    free(structure);
  }
  free(cpu_batched_DP);
  fprintf(stderr, "Completed CPU in %ld msec\n\n", accTime);
  fprintf(stdout, "Running again on GPU\n");
#endif // CPU_TARGET
  int* gpu_batched_DP = (int*)calloc(total_dp_cells, sizeof(int));
  nussinov_gpu_wrap(seqs, seq_offsets, seq_lengths, dp_offsets, N, total_bytes, total_dp_cells, gpu_batched_DP);

  for (size_t num_seq = 0; num_seq < N; num_seq++) {
    uint32_t len = seq_lengths[num_seq];
    uint8_t* curr_seq = &seqs[seq_offsets[num_seq]];
    int* curr_DP = &gpu_batched_DP[dp_offsets[num_seq]];

    // Traceback Setup
    int* DP_square = (int*)calloc(len * len, sizeof(int));
    cell_ind* structure = (cell_ind*)malloc(2 * len * sizeof(cell_ind));
    int struct_len = 0;

    // Copy uptriangular matrix to real NxN Matrix for this sequence
    for (int k = MIN_LOOP_LENGTH + 1; k < len; k++) {
      for (int i = 0; i < len - k; i++) {
        int j = i + k;
        DP_square[len * i + j] = curr_DP[triInd(i, j, len)];
      }
    }

    traceback(0, len-1, structure, DP_square, curr_seq, &struct_len, len);
    write_structure(len, structure, &struct_len);
  }

  free(gpu_batched_DP);
}

int main(int argc, char * const argv[]) {
  // nussinov sequence

  if (argc != 2) {
    std::cerr << "Usage: " << argv[0] << " <file-list.txt>\n" << std::endl;
    return 1;
  }

  // File String parsing by Gemini
  std::string listFileName = argv[1];
  std::ifstream listFile(listFileName);
  std::vector<std::string> myFiles;

  if (!listFile.is_open()) {
    std::cerr << "Error: Could not open list file " << listFileName << std::endl;
    return 1;
  }

  std::string currentFile;
  while (std::getline(listFile, currentFile)) {
    // Simple check to ignore empty lines in the list file
    if (!currentFile.empty()) {
      myFiles.push_back(currentFile);
    }
  }

  listFile.close();

  if (myFiles.empty()) {
    std::cerr << "The list file was empty. No sequences to process." << std::endl;
    return 1;
  }

  int num_seqs = myFiles.size();

  // parse into seqs into contiguous block of memory and record sizes
  // Also encode sequence
  std::vector<std::string> parsedSequences = getCleanedSequences(myFiles);


  uint32_t N = parsedSequences.size();
  uint32_t* seq_lengths = (uint32_t*)malloc(N * sizeof(uint32_t));
  uint32_t* seq_offsets = (uint32_t*)malloc(N * sizeof(uint32_t));
  uint32_t* dp_offsets = (uint32_t*)malloc(N * sizeof(uint32_t));

  uint32_t total_bytes = 0;
  uint32_t total_dp_cells = 0;

  for (uint32_t i = 0; i < N; i++) {
    uint32_t len = parsedSequences[i].length();
    seq_lengths[i] = len;
    seq_offsets[i] = total_bytes;
    dp_offsets[i] = total_dp_cells;
    
    // Calculate 2-bit bytes needed for THIS sequence, rounding up to nearest byte
    uint32_t bytes_needed = (len + 3) / 4; 
    total_bytes += bytes_needed;
    
    // Calculate DP triangular matrix size for THIS sequence
    uint32_t n_dp = len - MIN_LOOP_LENGTH;
    if (len > MIN_LOOP_LENGTH) {
        total_dp_cells += (n_dp * (n_dp - 1)) / 2;
    }
  }

  uint8_t* seqs = (uint8_t*)calloc(total_bytes, sizeof(uint8_t));

  for (uint32_t i = 0; i < N; i++) {
      encSeq(parsedSequences[i], &seqs[seq_offsets[i]], 0, seq_lengths[i]);
  }

  nussinov(seqs, seq_offsets, seq_lengths, dp_offsets, N, total_bytes, total_dp_cells);

  free(seq_lengths);
  free(seq_offsets);
  free(dp_offsets);
  free(seqs);
}
