/* ECE213 Final Project
 * Authors: Francisco Gutierrez, Jaehyung Lim, Sean Lipps
 *
 * Code Nussinov Algorithm
 * Reference Python: https://github.com/cgoliver/Nussinov
 *
 * Date of Creation: 2/24/26
 * Date Last Modified: 2/25/26
 */



#include <cstdlib>
#include <cstdio>
#include <cstring>

#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <cctype>


#include <bits/stdc++.h> // max function

#include "nussinov.cuh"


void show_DP(int* DP, int N){
  printf("Showing DP scores: \n");
  for(int i = 0; i<N; i++){
    for(int j = 0; j<N; j++){
      if(i < j - MIN_LOOP_LENGTH ) {
        printf("%3d ", DP[triInd(i, j, N)] );
      } else {
        printf("    ");
      } }
    printf("\n");
  }
}

// Parser generated by Gemini
// This function takes in a vector of .seq filesand returns a vector of them parsed
std::vector<std::string> getCleanedSequences(const std::vector<std::string>& fileNames) {
    std::vector<std::string> allSequences;

    for (const std::string& fileName : fileNames) {
        std::ifstream file(fileName);
        if (!file.is_open()) {
            std::cerr << "Could not open file: " << fileName << std::endl;
            continue;
        }

        std::string line;
        std::string currentSequence = "";
        bool headerSkipped = false;

        while (std::getline(file, line)) {
            if (line.empty() || line[0] == ';') continue;

            if (!headerSkipped) {
                headerSkipped = true;
                continue;
            }

            for (char c : line) {
                if (std::isspace(c) || c == '1') continue;
                currentSequence += c;
            }
        }

        if (!currentSequence.empty()) {
            allSequences.push_back(currentSequence);
        }
        file.close();
    }
    return allSequences;
}

void traceback(int i, int j, cell_ind* structure, int* DP, const uint8_t* seq, int* trace_len, int N) {
  if (j<=i){
    return;
  } else if ( DP[N*i+ j] == DP[N*i+ j-1] ){
    traceback(i, j-1, structure, DP, seq, trace_len, N);
  } else {
    for(int k = i; k < j-MIN_LOOP_LENGTH; k++) {
      if(pair_check(seq, k, j)){
        if (k-1<0) {
          if( DP[N*i+ j] ==  DP[N*(k+1)+ j-1] + 1) {
            structure[*trace_len].x = k;
            structure[*trace_len].y = j;
            (*trace_len)++;
            traceback(k+1, j-1, structure, DP, seq, trace_len, N);
            break;
          }
        } else if ( DP[N*i+j] == (
                      DP[N*(i)+k-1]
                    + DP[N*(k+1)+ j-1]
                    + 1
                  )) {
          // add the pair (j,k) to our list of pairs
          structure[*trace_len].x = k;
          structure[*trace_len].y = j;
          (*trace_len)++;
          // move the recursion to two substructures formed by this pairing
          traceback(i, k-1, structure, DP, seq, trace_len, N);
          traceback(k+1, j-1, structure, DP, seq, trace_len, N);
          break;
        }
      }
    }
  }
}

void write_structure(int N, cell_ind* structure, int* struct_len){
  char* dot_bracket = (char*)malloc(2*N+1);
  dot_bracket[N] = '\0';
  for(int i = 0; i<N; i++)
    dot_bracket[i]='.';

  for(int i = 0; i < *struct_len; i++){
    dot_bracket[std::min(structure[i].x, structure[i].y)] = '(';
    dot_bracket[std::max(structure[i].x, structure[i].y)] = ')';
  }

  bool put_comma = false;
  printf("('%s', [", dot_bracket);
  for(int i = 0; i < *struct_len; i++){
    if(put_comma) printf(", ");
    printf("(%d, %d)", structure[i].x, structure[i].y);
    put_comma = true;
  }
  printf("])\n");
  
  free(dot_bracket);
}

void nussinov_cpu(uint8_t* seq, int* DP, int N){
  int cell_value;
  int j;

  for(int k = MIN_LOOP_LENGTH+1; k < N; k++){
    for(int i = 0; i < (N-k); i++){
      j = i+k;

      if (i >= j- MIN_LOOP_LENGTH)
        cell_value = 0;
      else {
#if MIN_LOOP_LENGTH == 0
        // we do not want to go out of bounds
        if(j==0) cell_value = 0;
        else cell_value = DP[triInd(i, j-1, N)];
#else
        cell_value = DP[triInd(i, j-1, N)];
#endif


        // iterates through possible pairs for a cell
        for(int t = i; t< j-MIN_LOOP_LENGTH; t++){
          // Check paired scores (if pairing exists)
          if (pair_check(seq, t, j)) {
            int pairing1 = 0;
            int pairing2 = 0;

            if(i < (t-1)-MIN_LOOP_LENGTH)
              pairing1 = DP[triInd(i, t-1, N)];
            if(t+1 < (j-1)-MIN_LOOP_LENGTH)
              pairing2 = DP[triInd(t+1, j-1, N)];

            cell_value = std::max(cell_value, pairing1 + pairing2 + 1);
          }
        }
      }

      DP[triInd(i, j, N)] = cell_value;
    }
  }
}

/**
 * @brief Wrapper for running nussinov algorithm. 
 *
 * @param seqs array rna sequences contiguous and with 2 bit encoding
 * @param seqs_offsets determines what item endsin what place
 * @param N determines number of rna sequences in that encoded array
 * @param rp HAs runtime parameters for choosing what variations to do
 */
void nussinov(uint8_t* seqs, int* seqs_offsets, int N, runtimeParams rp){
  cell_ind *structure; // array tracing
  int* struct_len;
  int d_struct_len;
  struct_len = &d_struct_len; // may just want to ommit the pointer all together

#ifdef CPU_TARGET

  if(rp.cpuEnable) {

    int start_seq = 0;
    for(size_t num_seq = 0; num_seq < N; num_seq++) {
      int n = start_seq - seqs_offsets[num_seq];

      structure = (cell_ind*)malloc(2*n*sizeof(cell_ind)); 
      
      // annoying but needed for traceback
      int* DP_square = (int*)malloc(n*n*sizeof(int));

      int* DP = (int*)malloc( (((N-MIN_LOOP_LENGTH)*(N-MIN_LOOP_LENGTH-1)) /2 )*sizeof(int));

      nussinov_cpu(seqs, DP, seqs_offsets);

#ifdef DEBUG
      show_DP(DP, N);
#endif

      // we allocate in bulk since we do not know the final traceback size
      // Using vectors may hurt us since these types do not exist and are 
      // not transferrable to GPUs
      *struct_len = 0;

      // Copy uptriangular matrix to real NxN Matrix
      for(int k = MIN_LOOP_LENGTH+1; k < N; k++){
        for (int i = 0; i < N-k; i++){
          int j = i+k;
          DP_square[N*i+j] = DP[triInd(i, j, N)];
        }
      }

      // uses square for traceback
      traceback(0, N-1, structure, DP_square, seqs, struct_len, seqs_offsets);

      write_structure(N, structure, struct_len);

      free(DP_square);
      free(structure);

      printf("Running again on GPU\n");
  }
#endif // CPU_TARGET

  *struct_len = 0;

  nussinov_gpu_wrap(seq, structure, struct_len, N);

    int* DP = (int*)malloc( (((N-MIN_LOOP_LENGTH)*(N-MIN_LOOP_LENGTH-1)) /2 )*sizeof(int));


    nussinov_gpu_wrap(seq, DP_square, N);

    *struct_len = 0;

    traceback(0, N-1, structure, DP_square, seq, struct_len, N);

    write_structure(N, structure, struct_len);
  }

#ifdef CPU_TARGET
  if(rp.cpuEnable){
    free(DP);
  }
#endif
}

int main(int argc, char * const argv[]) {
  // nussinov sequence

  if (argc != 2) {
    std::cerr << "Usage: " << argv[0] << " <file-list.txt>\n" << std::endl;
    return 1;
  }

  // enable CPU, disable GPU
  runtimeParams rp;
  rp.gpuEnable = false;
  rp.cpuEnable = false;

  // File String parsing by Gemini
  std::string listFileName = argv[1];
  std::ifstream listFile(listFileName);
  std::vector<std::string> myFiles;

  if (!listFile.is_open()) {
    std::cerr << "Error: Could not open list file " << listFileName << std::endl;
    return 1;
  }

  std::string currentFile;
  while (std::getline(listFile, currentFile)) {
    // Simple check to ignore empty lines in the list file
    if (!currentFile.empty()) {
      myFiles.push_back(currentFile);
    }
  }

  listFile.close();

  if (myFiles.empty()) {
    std::cerr << "The list file was empty. No sequences to process." << std::endl;
    return 1;
  }

  int num_seqs = myFiles.size();

  // parse into seqs into contiguous block of memory and record sizes
  // Also encode sequence
  std::vector<std::string> parsedSequences = getCleanedSequences(myFiles);


  uint32_t N = parsedSequences.size();
  uint8_t *seqs;
  uint32_t *seqs_offsets = (uint32_t*)calloc(parsedSequences.size(), sizeof(uint32_t));


  {
    uint32_t offset_counter = 0;
    for (uint32_t i = 0; i < N; i++) {
      offset_counter = parsedSequences[i].length();
      offset_counter += parsedSequences[i].length();
      seqs_offsets[i]      = offset_counter;
    }

    seqs = (uint8_t*)calloc((offset_counter+3)/4, sizeof(uint8_t));

    uint32_t next_ind = 0;
    for (uint32_t i = 0; i < N; i++) {
      encSeq(parsedSequences[i], seqs, next_ind, seqs_offsets[i]);
      next_ind = seqs_offset[i];
    }
  }

  nussinov(seqs, seqs_offsets, rp, N);

  free(seqs_lens);
  free(seqs);
}
